### ISSUE TITLE
google authentication fails on ios

### ISSUE THREAD

**Issue by charliepank** [mirzemehdi/KMPAuth#12]
Hi, with all the correct info in the plist files, I can push the button to log in using google, it launches safari on accounts.google.com page, and produces an error: 
- access blocked authorization error
- missing required parameter: redirect_uri
- error 400L: invalid request

**Comment by charliepank** [comment]
<img width="387" alt="Screenshot 2024-03-19 at 10 41 52" src="https://github.com/mirzemehdi/KMPAuth/assets/6232906/92dcebe0-3d57-4a41-9597-1a87e28c8dc3">

**Comment by mirzemehdi** [comment]
Probably, there is an issue with custom url schemes in iOS side. Please make sure you followed all steps in Firebase Google Sign-In for iOS.

https://firebase.google.com/docs/auth/ios/google-signin

**Comment by mirzemehdi** [comment]
This issue is not related to library itself, so I'll close this.

**Comment by charliepank** [comment]
Hey, I just came back to say - yes you're absolutely right. It is now working like a charm. I don't even know what was causing the issue, I spent some (a lot) of time rebuilding the iOS project from the ground up, and now it works. Wow iOS devt environment is horrible!
