### ISSUE TITLE
I used R8 android, it do google sign-in not working.

### ISSUE THREAD

**Issue by thanhhoai162963** [mirzemehdi/KMPAuth#18]
I used R8 android, it do google sign-in not working.
I added keep but not working.
```
-keep public interface com.mmk.kmpauth.google.GoogleAuthProvider { *; }
-dontwarn com.mmk.kmpauth.google.GoogleAuthProvider.**
-keep class com.mmk.kmpauth.google.GoogleAuthProvider$Companion
-keep class com.mmk.kmpauth.google.GoogleAuthUiProviderImpl
-keep class com.mmk.kmpauth.core.di.KMPKoinComponent
-keep class com.mmk.kmpauth.google.GoogleAuthProvider  { *; }
```

**Comment by mirzemehdi** [comment]
@thanhhoai162963 Could you please add error log, what happens when try it with R8 enabled?

**Comment by mirzemehdi** [comment]
@thanhhoai162963 

https://developer.android.com/training/sign-in/passkeys#proguard

From official documentation: "In your module's proguard-rules.pro file, add the following directives:"
```
-if class androidx.credentials.CredentialManager
-keep class androidx.credentials.playservices.** {
  *;
}
```

**Comment by mirzemehdi** [comment]
Also please check this proguard rules as well

https://github.com/googlesamples/google-signin-unity/issues/159#issuecomment-704021107
https://github.com/googlesamples/google-signin-unity/issues/144#issuecomment-661287480
