### ISSUE TITLE
Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: 

### ISSUE THREAD

**Issue by mirzemehdi** [mirzemehdi/KMPAuth#2]
When implementing kmpauth-uihelper module, Android builds and works normally. But in iOS it crashes with runtime error.
Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path:

**Comment by mirzemehdi** [comment]
For some reason compose-resources aren't visible in iOS side.

Solution: 

**First Step:**  in your shared module in iosMain sourceSet create `resources` directory  (if not exists), and download `Resources`, unzip and copy as below image.
[Resources](https://github.com/mirzemehdi/KMPAuth/files/14002221/resources.zip)

<img width="462" alt="image" src="https://github.com/mirzemehdi/KMPAuth/assets/32781662/be3db0fb-1554-4bc7-99d9-0353d0d0674a">  


**Second step**: in `build.gradle` file set resources directory as below
```
iosMain {
  resources.srcDirs("src/commonMain/resources","src/iosMain/resources")
  dependencies {
    //Your dependencies
  }
}
```

**Comment by powext** [comment]
Same problem here, with 
kotlin = "2.2.0"
compose-multiplatform = "1.8.1"

Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: /private/var/containers/Bundle/Application/56609637-1255-426D-B21A-C521F847FFF6/OptyMacros.app/compose-resources/composeResources/io.github.mirzemehdi.kmpauth_uihelper.generated.resources/drawable/ic_google.xml
