### ISSUE TITLE
Compose desktop support?

### ISSUE THREAD

**Issue by artalejo** [mirzemehdi/KMPAuth#27]
Hello there,

I am just wondering if you are planning to add support for jvm (compose desktop)

Thanks a lot in advance.

**Comment by mirzemehdi** [comment]
I have not planned it yet, will think about it if there is a need for that. But PR are welcome :)

Duplicate of https://github.com/mirzemehdi/KMPAuth/issues/15

**Comment by mirzemehdi** [comment]
For now desktop target is added but with dummy classes/and methods: https://github.com/mirzemehdi/KMPAuth/releases/tag/v2.1.0-alpha02

Closing this issue since duplicate issue exists: #15 . Thank you.
