### ISSUE TITLE
Can't build iOS

### ISSUE THREAD

**Issue by gabrieloterostride** [mirzemehdi/KMPAuth#33]
I'm following your iOS Setup, and at the moment I create the app delegate I have the following error

../iosApp/iosApp/AppDelegate.swift:33:17: error: cannot find 'GIDSignIn' in scope
                GIDSignIn.sharedInstance.handle(url)
                ^~~~~~~~~

Can you help me figuring it out?

**Comment by mirzemehdi** [comment]
@gabrieloterostride Please make sure you add Google Sign in Swift side as well.

I shared in this issue: https://github.com/mirzemehdi/KMPAuth/issues/6

**Comment by gabrieloterostride** [comment]
It worked! thanks!
