### ISSUE TITLE
Build fails when implementing KMPAuth

### ISSUE THREAD

**Issue by BehnamMaboodi** [mirzemehdi/KMPAuth#4]
When I implement KMPAuth in common source set,  builds for iOS result in failure with the following error message:
```
Task :shared:compileKotlinIosX64 FAILED
error: Could not find "org.jetbrains.compose.ui:ui-uikit-cinterop-utils" in [/Users/project name/Pods, /Users/project name/.konan/klib, /Users/projectname/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.21/klib/common, /Users/projectname/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.21/klib/platform/ios_x64]
```

**Comment by mirzemehdi** [comment]
@BehnamMaboodi 
1)Does this only happens for ios? and in Android it works?
2) Could you please make sure that in Xcode you added Firebase, and GoogleSignIn, Please try with Swift Package Manager as well.

**Comment by BehnamMaboodi** [comment]
Thanks for your help
It was related to compose version conflict.
