### ISSUE TITLE
GoogleLegacyAuth Error: com.google.android.gms.common.api.ApiException: 10:

### ISSUE THREAD

**Issue by Creat0r69** [mirzemehdi/KMPAuth#41]
When i try to Sign in with goole i get this error 'GoogleLegacyAuth Error: com.google.android.gms.common.api.ApiException: 10'
and token return null and the sheet closed 
2024-07-31 10:59:57.166  3888-5333  BufferQueueProducer     surfaceflinger                       E  [healthcare_system.androidApp/com.google.android.gms.auth.api.signin.internal.SignInHubActivity$_23500#0](id:f300000012a,api:0,p:-1,c:3888) disconnect: not connected (req=1)

i double check SHA1 key it's the correct one and i checked the ID client also correct 
i've been stuck on this error for like 3 days now i need help

**Comment by Creat0r69** [comment]
i did that

**Comment by Creat0r69** [comment]
https://www.youtube.com/watch?v=mLfqCyO8-Bc followed this tuto step by step he is using KMPAuth lib

**Comment by Creat0r69** [comment]
![image](https://github.com/user-attachments/assets/cd5c47de-eb9d-422b-8d43-904d66e59bd1)
used this one

**Comment by mirzemehdi** [comment]
maybe your `google-services.json` file is the old one if you use firebase, and after enabling google auth from firebase download `google-services.json` file and try again

**Comment by Creat0r69** [comment]
i don't use firebase

**Comment by mirzemehdi** [comment]
check with other devices/emulator see if still happens.

**Comment by Creat0r69** [comment]
still same error and i didn't add google-services.json i added client id directly 
![image](https://github.com/user-attachments/assets/c7012901-8844-4ae5-8b01-15a0be410c01)
![image](https://github.com/user-attachments/assets/2b64d24b-70dd-4741-b175-c315a3bc646a)
![image](https://github.com/user-attachments/assets/adcf3a88-93f7-40ab-8a3a-046f6fbb2233)

**Comment by Creat0r69** [comment]
i also get this 
GoogleAuthUiProvider error: During begin sign in, failure response from one tap: 10: [28444] Developer console is not set up correctly.

**Comment by mirzemehdi** [comment]
@Creat0r69 
Attaching related solutions:

https://support.google.com/googleplay/android-developer/thread/233538051/one-tap-sign-in-not-working-on-production?hl=en

https://stackoverflow.com/questions/76823978/error-10-developer-console-is-not-set-up-correctly-not-using-firebase-one-t

Closing this issue as it not related library, but more about some configuration issue.
