### ISSUE TITLE
Cannot override the size of GoogleButtonUiContainer or GoogleSignInButtonIconOnly

### ISSUE THREAD

**Issue by KawtharE** [mirzemehdi/KMPAuth#46]
Hey, 
first thank you so much for this amazing library, it's really helping a lot :) 

I am facing problem changing the size of the button, as it's only 40.dp and in my case that's not enough, i wonder if it's possible to make it possible to override the default size of the buttons.

thank you

**Comment by mirzemehdi** [comment]
@KawtharE it should be configurable.

example
```kotlin

GoogleSignInButton(
    modifier = Modifier.fillMaxWidth().height(64.dp),
    fontSize = 20.sp,
    mode = if (isDarkMode) GoogleButtonMode.Dark else GoogleButtonMode.Light,
    shape = shape) { this.onClick() }

```

Please check https://mirzemehdi.com/KMPAuth/kmpauth-uihelper/com.mmk.kmpauth.uihelper.google/-google-sign-in-button.html
