### ISSUE TITLE
Firebase failed to Solve [Auth and Common KTX]

### ISSUE THREAD

**Issue by santyas** [mirzemehdi/KMPAuth#58]
Hello! Could that errors be related to this library?

![firebase-error](https://github.com/user-attachments/assets/a78a1b3f-2aa6-4ff6-b9da-c25fe3ca38cf)

Could I have missed something with kmpauth setup?

Thank you!

**Comment by santyas** [comment]
> Task :composeApp:generateDebugAndroidTestLintModel FAILED

FAILURE: Build failed with an exception.

* What went wrong:
`Execution failed for task ':composeApp:generateDebugAndroidTestLintModel'.
> Could not resolve all files for configuration ':composeApp:debugAndroidTestCompileClasspath'.
   > Could not find com.google.firebase:firebase-auth-ktx:.
     Required by:
         project :composeApp > io.github.mirzemehdi:kmpauth-firebase:2.1.0 > io.github.mirzemehdi:kmpauth-firebase-android-debug:2.1.0 > dev.gitlive:firebase-auth:2.1.0 > dev.gitlive:firebase-auth-android-debug:2.1.0
   > Could not find com.google.firebase:firebase-common-ktx:.
     Required by:
         project :composeApp > io.github.mirzemehdi:kmpauth-firebase:2.1.0 > io.github.mirzemehdi:kmpauth-firebase-android-debug:2.1.0 > dev.gitlive:firebase-auth:2.1.0 > dev.gitlive:firebase-auth-android-debug:2.1.0 > dev.gitlive:firebase-app:2.1.0 > dev.gitlive:firebase-app-android-debug:2.1.0`

**Comment by mirzemehdi** [comment]
@santyas which targets your project support? Only android and ios?

Also you can try to add this library to see if it is solved:

```
implementation("dev.gitlive:firebase-auth:2.1.0")
```

**Comment by mirzemehdi** [comment]
I also get those but only as warning, it doesn't cause any error

**Comment by mirzemehdi** [comment]
Looks like problem comes from Firebae Gitlive lib. 

Related issue: https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/356

Okay so solution is to add these dependencies in your `androidMain` sourceSet

```
implementation("com.google.firebase:firebase-common-ktx:21.0.0")
implementation("com.google.firebase:firebase-auth-ktx:21.0.0")
```

**Comment by santyas** [comment]
Ok so should I add gitlive lib?

**Comment by mirzemehdi** [comment]
you will not need to add that probably only above two implementation should solve the issue

**Comment by santyas** [comment]
Good catch! No errors! I have kept all 3 and it works. Yes Im working on in a android & ios project only.

Im sharing my gradle configuration with you if you want to test kmpauth with those recent dependency versions:
https://gist.github.com/santyas/5a79f1d997a571c3ebfb8d0354c8ffee

Thank you!
