### ISSUE TITLE
Need help in adding googleSignIn package in ios app

### ISSUE THREAD

**Issue by gulabsagevadiya** [mirzemehdi/KMPAuth#6]
There is no discussion forum in this repo so i have created this issue. 
I am new to kmp and i have only exp with android development so it's little confusing to add packages to ios app.
can you help us by creating step by step process to add package in ios with cocoapods

i have already added cocoapods on my mac system but you can start from this to help other like me

**Comment by mirzemehdi** [comment]
I personally use Swift Package Manager for adding dependencies in iOS. Here's how to do it in XCode.
File -> Add Package Dependencies -> Entering "https://github.com/google/GoogleSignIn-iOS" in url field -> Add Package Button. 

<img width="1210" alt="image" src="https://github.com/mirzemehdi/KMPAuth/assets/32781662/b000e494-0064-46e2-9a9a-c32d5c919870">

**Comment by gulabsagevadiya** [comment]
Appreciate your efforts for junior developer like me.
And yes this is way easier then cocoapods

**Comment by usmonie** [comment]
I added the GoogleSignIn library to the project via SPM, but the build continues to fall with an error:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: framework 'GoogleSignIn' not found
```
