### ISSUE TITLE
[Nice to have] Apple SignIn Button with mode BlackWithOutline

### ISSUE THREAD

**Issue by erickvelasco11** [mirzemehdi/KMPAuth#64]
Hi
Thanks for all your work here, this have been really helpfully in our work.

Just a nice to have. Implement the BlackWithOutline. This for keep the style of the buttons in dark mode.

i.e.
This is my login page with light mode
![white](https://github.com/user-attachments/assets/89d9d25d-780f-4efe-a831-09f6bc7aadf6)

But this is my login page in dark mode. The apple button is like a bulb on and the mode "black" is worst in dark mode
![black](https://github.com/user-attachments/assets/0ab9a43d-5bdb-40f3-8949-3b63d8f42c5c)

However, this is not impacting the functionality.

Thanks again for your work

**Comment by mirzemehdi** [comment]
@erickvelasco11 thanks for suggestion but official Apple guideline suggest only 3 modes of Button:

White, White with Outline, Black

All of these three are provided by library. 

https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple#sign-in-with-apple-buttons

Closing the issue
