### ISSUE TITLE
Apple sign-in does not work in android sample app

### ISSUE THREAD

**Issue by shalva97** [mirzemehdi/KMPAuth#71]
fails with. Any ideas how to fix this?

```
[GetAuthDomainTask] IOException occurred: Failed to connect to www.googleapis.com/[2a00:1450:4017:816::200a]:443
Error Result: An internal error has occurred.
```

**Comment by mirzemehdi** [comment]
@shalva97 Interesting. if you use firebase apple sign in, maybe it is blocked some firewall?

In terminal you can check `ping android.googleapis.com` to see if it is blocked

**Comment by shalva97** [comment]
I will close this. not sure what happened yesterda. today it shows another error
