### ISSUE TITLE
Unsolved reference 'onClick'

### ISSUE THREAD

**Issue by erwinkaaa** [mirzemehdi/KMPAuth#74]
Hi, I'm trying the library with version 2.3.0-beta01 and got error.

My implementation :
```
GoogleButtonUiContainerFirebase(
          linkAccount = false,
          onResult = { result ->
                when {
                     result.isSuccess -> {
                                println("Test")
                     }
                     result.isFailure -> {
                            
                     }
                }
          },
          content = {
                 Button(onClick = { this.onClick() }) { Text("Google Sign-In(Custom Design)") }
          }
)
```

I got error `Unresolved reference 'onClick'.`

How to fix this?

**Comment by shalva97** [comment]
Just copy pasted it in my project and it works. Maybe you are writting it in wrong source set? I tried it in commonMain

**Comment by erwinkaaa** [comment]
> Just copy pasted it in my project and it works. Maybe you are writting it in wrong source set? I tried it in commonMain

Yes it is in commonMain, but still cant build because the error

**Comment by theGBguy** [comment]
> > Just copy pasted it in my project and it works. Maybe you are writting it in wrong source set? I tried it in commonMain
> 
> Yes it is in commonMain, but still cant build because the error

```
Cannot access class 'com.mmk.kmpauth.core.UiContainerScope'. Check your module classpath for missing or conflicting dependencies.
Unresolved reference 'onClick'.
```
I am also getting this error in commonMain source set. Very strange.

**Comment by theGBguy** [comment]
> > Just copy pasted it in my project and it works. Maybe you are writting it in wrong source set? I tried it in commonMain
> 
> Yes it is in commonMain, but still cant build because the error

@erwinkaaa I included all 3 dependencies and it worked. Looks like one meant for Google One Tap Sign in is also required even if you just want to use Google Sign In with Firebase.
```
            implementation(libs.kmpauth.google)
            implementation(libs.kmpauth.firebase)
            implementation(libs.kmpauth.uihelper)
```
