### ISSUE TITLE
[iOS] Google Sign In got error 400 Invalid_request

### ISSUE THREAD

**Issue by 658jjh** [mirzemehdi/KMPAuth#76]
Android works fine, and the apple login for iOS works fine, but can not make it work for login google.
The setup is basically same as your readme, except this:

```
<key>GIDServerClientID</key>
<string>YOUR_SERVER_CLIENT_ID</string>

<key>GIDClientID</key>
<string>YOUR_IOS_CLIENT_ID</string>
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>YOUR_DOT_REVERSED_IOS_CLIENT_ID</string>
    </array>
  </dict>
</array>
```

is this from GoogleService-Info.plist if it's not then what is that? and where can I find that?

**Comment by codlab** [comment]
from your google console (not firebase), you need to find (or create) a oauth entry made for iOS from the credentials page and then copy the client id (+ reverse the id as well for the CFBundleURLSchemes)
